### ISSUE TITLE
toolbox isn't working

### ISSUE THREAD

**Issue by jdthomps4** [mraad/bulk-geo-es#1]
just by downloading the tool and opening in ArcMap...  We get these syntax errors:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy__init__.py", line 24, in <module>
    from arcpy.toolbox import *
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\toolbox.py", line 355, in <module>
    from .management import Graph, GraphTemplate
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy\management.py", line 26, in <module>
    import _management
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy_management.py", line 14, in <module>
    import _graph
  File "c:\program files (x86)\arcgis\desktop10.3\arcpy\arcpy_graph.py", line 27, in <module>
    import numpy
ImportError: No module named numpy

Any suggestions?  Are we loading toolbox from wrong place?  I have ensured numpy is downloaded...

Thanks!

Jessica

**Comment by mraad** [comment]
Did u adjust the PATH env variable ?

**Comment by jdthomps4** [comment]
Yes... and the command line says my elasticsearch is up to date... 
Do I need to place the tool in a certain folder?

**Comment by jdthomps4** [comment]
![image](https://cloud.githubusercontent.com/assets/11876378/10172374/f4762764-66ac-11e5-878c-45cf145494d5.png)

Path is updated... still get the same error...

i reran the install for elasticsearch through pip

![image](https://cloud.githubusercontent.com/assets/11876378/10173717/dafbddea-66b3-11e5-8e48-1ec7144f97d0.png)

**Comment by jdthomps4** [comment]
got it all straightened out...

**Comment by mraad** [comment]
Please elaborate

**Comment by GISDev01** [comment]
@jdthomps4 Also interested in how you fixed it.

**Comment by jdthomps4** [comment]
uninstalled and reinstalled arcmap and python... python had gone corrupt.... essentially started from scratch
